apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas-svmdr
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  selector: "backend=svmdr"
allowVolumeExpansion: True
