apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ontap-nas
  resources:
    requests:
        storage: 10Gi
